# Generated by Django 2.1.2 on 2018-10-13 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WeiboAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MblogComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author_set', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mblog',
            name='thumb',
            field=models.ManyToManyField(related_name='blog_thumb_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mblogfile',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_files_set', to='WeiboAPP.Mblog'),
        ),
        migrations.AddField(
            model_name='mblogcomment',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_blog_set', to='WeiboAPP.Mblog'),
        ),
    ]
