# Generated by Django 2.1.2 on 2018-10-24 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboAPP', '0003_auto_20181014_1157'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='myself',
        ),
        migrations.AlterField(
            model_name='mblogcomment',
            name='refer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_refer_set', to='WeiboAPP.MblogComment'),
        ),
        migrations.DeleteModel(
            name='test',
        ),
    ]
