# Generated by Django 3.0.6 on 2020-05-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboAPP', '0004_auto_20181024_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mblogfile',
            name='file',
            field=models.CharField(max_length=100),
        ),
    ]
