# Generated by Django 3.0.6 on 2020-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WeiboAPP', '0005_auto_20200512_2051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mblog',
            options={'verbose_name': '用户动态', 'verbose_name_plural': '用户动态'},
        ),
        migrations.AlterModelOptions(
            name='mblogfile',
            options={'verbose_name': '用户动态附件', 'verbose_name_plural': '用户动态附件'},
        ),
    ]
