# Generated by Django 3.0.6 on 2020-05-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pytorchDemo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypic',
            options={'verbose_name': '用户图片', 'verbose_name_plural': '用户图片'},
        ),
        migrations.AlterField(
            model_name='mypic',
            name='picAfter',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mypic',
            name='picBefore',
            field=models.CharField(max_length=100),
        ),
    ]
