# Generated by Django 3.0.6 on 2020-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pytorchDemo', '0002_auto_20200512_2035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mypic',
            options={'verbose_name': '用户图册', 'verbose_name_plural': '用户图册'},
        ),
    ]
