# Generated by Django 3.0.6 on 2020-05-12 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExploreAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
