# Generated by Django 2.1.2 on 2018-10-24 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('build_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalDetials',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('avatar', models.FilePathField()),
                ('phone', models.CharField(max_length=11)),
                ('bg_img', models.FilePathField()),
                ('introduction', models.TextField()),
                ('address', models.TextField()),
                ('follow', models.ManyToManyField(through='MyCenterAPP.Follow', to='MyCenterAPP.PersonalDetials')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='follow',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers_set', to='MyCenterAPP.PersonalDetials'),
        ),
        migrations.AddField(
            model_name='follow',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_set', to='MyCenterAPP.PersonalDetials'),
        ),
    ]
