# Generated by Django 3.0.6 on 2020-05-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('pic', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=50)),
                ('desc', models.TextField()),
                ('att_cnt', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': '比赛信息',
                'verbose_name_plural': '比赛信息',
            },
        ),
    ]
