# Generated by Django 3.0.6 on 2020-05-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='start_time',
            field=models.CharField(default='2020年3月9日', max_length=50),
            preserve_default=False,
        ),
    ]
