# Generated by Django 3.0.6 on 2020-05-13 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MainAPP', '0002_competition_start_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.CharField(max_length=100)),
                ('create_time', models.CharField(default='2020年5月12日', max_length=100)),
                ('upload_time', models.CharField(default='2020年5月13日', max_length=100)),
                ('desc', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comppic_user_set', to=settings.AUTH_USER_MODEL)),
                ('comp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comppic_comp_set', to='MainAPP.Competition')),
            ],
            options={
                'verbose_name': '比赛作品管理',
                'verbose_name_plural': '比赛作品管理',
            },
        ),
    ]
